name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  bundle:
    description: Path to the already-bundled Node code.
    required: true

# Define your outputs here.
outputs:
  binary-path:
    description: The filesystem path to the Node binary with the code embedded.

runs:
  using: node20
  main: dist/index.js
