name: Build Node single executable application
description:
  Use the experimental "--experimental-sea-config" to build a single executable
author: Jason Gwartz

branding:
  icon: 'user-plus'
  color: 'green'

inputs:
  bundle:
    description: Path to the already-bundled Node code
    required: true
  name:
    description: The filename of the output binary (defaults to the repo name)
  upload-artifact:
    description:
      If true, the resulting binary will be uploaded as a "workflow artifact"
      (defaults to true)
    default: true

outputs:
  binary-path:
    description: The filesystem path to the Node binary with the code embedded

runs:
  using: node20
  main: dist/index.js
