name: Build Node single executable application
description:
  Use the experimental "--experimental-sea-config" to build a single executable
author: Jason Gwartz

branding:
  icon: 'user-plus'
  color: 'green'

inputs:
  bundle:
    description: Path to the already-bundled Node code
    required: true
  name:
    description: The filename of the output binary (defaults to the repo name)
  assets:
    description:
      A comma-separated or newline-separated list of files to be included in the
      executable as "SEA assets" (see the SEA documentation on how to use the
      "node:sea" package to retrieve these assets in code)
  upload-workflow-artifact:
    description:
      If any truthy string, the resulting binary will be uploaded as a "workflow
      artifact" (defaults to "1")
    default: '1'

outputs:
  binary-path:
    description: The filesystem path to the Node binary with the code embedded

runs:
  using: node20
  main: dist/index.js
